export interface Language {
  code: string;
  label: string;
  nativeLabel: string;
  greeting: string;
}

export const languages: Language[] = [
  { code: "en", label: "English", nativeLabel: "English", greeting: "Hello!" },
  { code: "zh", label: "Chinese", nativeLabel: "华语", greeting: "你好！" },
  { code: "ms", label: "Malay", nativeLabel: "Bahasa Melayu", greeting: "Selamat!" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்", greeting: "வணக்கம்!" },
  { code: "hk", label: "Hokkien", nativeLabel: "福建话", greeting: "你好！" },
  { code: "ct", label: "Cantonese", nativeLabel: "广东话", greeting: "你好！" },
  { code: "tc", label: "Teochew", nativeLabel: "潮州话", greeting: "汝好！" },
];

// Simple translations for UI elements
export const translations: Record<string, Record<string, string>> = {
  en: {
    appName: "Ah Gong Ah Ma Helper",
    tagline: "We make things simple for you",
    scanButton: "📷  Scan & Explain",
    scanSubtext: "Take a photo of anything you need help with",
    historyTitle: "Recent Help",
    languageTitle: "Choose Your Language",
    uploadTitle: "Scan Something",
    uploadDesc: "Take a photo or choose from your gallery",
    takePhoto: "📷  Take Photo",
    chooseGallery: "🖼️  Choose from Gallery",
    analyzing: "Reading your photo...",
    resultTitle: "Here's What It Means",
    backHome: "🏠  Go Home",
    scanAgain: "📷  Scan Again",
    changeLang: "Change Language",
  },
  zh: {
    appName: "阿公阿嬷帮手",
    tagline: "我们帮你简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张照片，我们帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "选择语言",
    uploadTitle: "扫描东西",
    uploadDesc: "拍照或从相册选择",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选择",
    analyzing: "正在看你的照片...",
    resultTitle: "意思是这样的",
    backHome: "🏠  回首页",
    scanAgain: "📷  再扫描",
    changeLang: "更换语言",
  },
  ms: {
    appName: "Pembantu Datuk Nenek",
    tagline: "Kami permudahkan untuk anda",
    scanButton: "📷  Imbas & Terang",
    scanSubtext: "Ambil gambar apa sahaja yang anda perlukan bantuan",
    historyTitle: "Bantuan Terkini",
    languageTitle: "Pilih Bahasa Anda",
    uploadTitle: "Imbas Sesuatu",
    uploadDesc: "Ambil gambar atau pilih dari galeri",
    takePhoto: "📷  Ambil Gambar",
    chooseGallery: "🖼️  Pilih dari Galeri",
    analyzing: "Membaca gambar anda...",
    resultTitle: "Ini Maksudnya",
    backHome: "🏠  Halaman Utama",
    scanAgain: "📷  Imbas Lagi",
    changeLang: "Tukar Bahasa",
  },
  ta: {
    appName: "தாத்தா பாட்டி உதவி",
    tagline: "நாங்கள் எளிமையாக்குவோம்",
    scanButton: "📷  ஸ்கேன் & விளக்கம்",
    scanSubtext: "உங்களுக்கு உதவி தேவையான எதையும் புகைப்படம் எடுங்கள்",
    historyTitle: "சமீபத்திய உதவி",
    languageTitle: "உங்கள் மொழியைத் தேர்வுசெய்க",
    uploadTitle: "ஸ்கேன் செய்யுங்கள்",
    uploadDesc: "புகைப்படம் எடுக்கவும் அல்லது கேலரியிலிருந்து தேர்வுசெய்யவும்",
    takePhoto: "📷  புகைப்படம் எடு",
    chooseGallery: "🖼️  கேலரியிலிருந்து தேர்வுசெய்",
    analyzing: "உங்கள் புகைப்படத்தைப் படிக்கிறது...",
    resultTitle: "இதன் பொருள் இதுதான்",
    backHome: "🏠  முகப்புக்குச் செல்",
    scanAgain: "📷  மீண்டும் ஸ்கேன்",
    changeLang: "மொழியை மாற்று",
  },
  hk: {
    appName: "阿公阿嬷帮手",
    tagline: "我们帮你简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张照片，我们帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "选择语言",
    uploadTitle: "扫描东西",
    uploadDesc: "拍照或从相册选择",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选择",
    analyzing: "正在看你的照片...",
    resultTitle: "意思是这样的",
    backHome: "🏠  回首页",
    scanAgain: "📷  再扫描",
    changeLang: "更换语言",
  },
  ct: {
    appName: "阿公阿嬷帮手",
    tagline: "我哋帮你简单解释",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "影张相，我哋帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "拣语言",
    uploadTitle: "扫描嘢",
    uploadDesc: "影相或者从相册拣",
    takePhoto: "📷  影相",
    chooseGallery: "🖼️  从相册拣",
    analyzing: "睇紧你张相...",
    resultTitle: "意思系咁嘅",
    backHome: "🏠  返首页",
    scanAgain: "📷  再扫描",
    changeLang: "换语言",
  },
  tc: {
    appName: "阿公阿嬷帮手",
    tagline: "阮共汝简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张相，阮共汝解释",
    historyTitle: "最近帮助",
    languageTitle: "选语言",
    uploadTitle: "扫描物件",
    uploadDesc: "拍照或从相册选",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选",
    analyzing: "在看汝的相片...",
    resultTitle: "意思是安呢",
    backHome: "🏠  转去首页",
    scanAgain: "📷  再扫描",
    changeLang: "换语言",
  },
};

export function t(lang: string, key: string): string {
  return translations[lang]?.[key] || translations.en[key] || key;
}
