export interface Language {
  code: string;
  label: string;
  nativeLabel: string;
  greeting: string;
}

export const languages: Language[] = [
  { code: "en", label: "English", nativeLabel: "English", greeting: "Hello!" },
  { code: "zh", label: "Chinese", nativeLabel: "华语", greeting: "你好！" },
  { code: "ms", label: "Malay", nativeLabel: "Bahasa Melayu", greeting: "Selamat!" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்", greeting: "வணக்கம்!" },
  { code: "hk", label: "Hokkien", nativeLabel: "福建话", greeting: "你好！" },
  { code: "ct", label: "Cantonese", nativeLabel: "广东话", greeting: "你好！" },
  { code: "tc", label: "Teochew", nativeLabel: "潮州话", greeting: "汝好！" },
];

export const otherLanguages: Language[] = [
  { code: "vi", label: "Vietnamese", nativeLabel: "Tiếng Việt", greeting: "Xin chào!" },
  { code: "th", label: "Thai", nativeLabel: "ภาษาไทย", greeting: "สวัสดี!" },
  { code: "ko", label: "Korean", nativeLabel: "한국어", greeting: "안녕하세요!" },
  { code: "ja", label: "Japanese", nativeLabel: "日本語", greeting: "こんにちは！" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी", greeting: "नमस्ते!" },
];

// Simple translations for UI elements
export const translations: Record<string, Record<string, string>> = {
  en: {
    appName: "SteadyLA",
    tagline: "We make things simple for you",
    scanButton: "📷  Scan & Explain",
    scanSubtext: "Take a photo of anything you need help with",
    historyTitle: "Recent Help",
    languageTitle: "Choose Your Language",
    uploadTitle: "Scan Something",
    uploadDesc: "Take a photo or choose from your gallery",
    takePhoto: "📷  Take Photo",
    chooseGallery: "🖼️  Choose from Gallery",
    analyzing: "Reading your photo...",
    resultTitle: "Here's What It Means",
    backHome: "🏠  Go Home",
    scanAgain: "📷  Scan Again",
    changeLang: "Change Language",
    textSize: "Text Size",
    listenButton: "🔊  Listen",
    stopButton: "⏹️  Stop",
  },
  zh: {
    appName: "SteadyLA",
    tagline: "我们帮你简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张照片，我们帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "选择语言",
    uploadTitle: "扫描东西",
    uploadDesc: "拍照或从相册选择",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选择",
    analyzing: "正在看你的照片...",
    resultTitle: "意思是这样的",
    backHome: "🏠  回首页",
    scanAgain: "📷  再扫描",
    changeLang: "更换语言",
    textSize: "文字大小",
    listenButton: "🔊  听一听",
    stopButton: "⏹️  停止",
  },
  ms: {
    appName: "SteadyLA",
    tagline: "Kami permudahkan untuk anda",
    scanButton: "📷  Imbas & Terang",
    scanSubtext: "Ambil gambar apa sahaja yang anda perlukan bantuan",
    historyTitle: "Bantuan Terkini",
    languageTitle: "Pilih Bahasa Anda",
    uploadTitle: "Imbas Sesuatu",
    uploadDesc: "Ambil gambar atau pilih dari galeri",
    takePhoto: "📷  Ambil Gambar",
    chooseGallery: "🖼️  Pilih dari Galeri",
    analyzing: "Membaca gambar anda...",
    resultTitle: "Ini Maksudnya",
    backHome: "🏠  Halaman Utama",
    scanAgain: "📷  Imbas Lagi",
    changeLang: "Tukar Bahasa",
    textSize: "Saiz Teks",
    listenButton: "🔊  Dengar",
    stopButton: "⏹️  Berhenti",
  },
  ta: {
    appName: "SteadyLA",
    tagline: "நாங்கள் எளிமையாக்குவோம்",
    scanButton: "📷  ஸ்கேன் & விளக்கம்",
    scanSubtext: "உங்களுக்கு உதவி தேவையான எதையும் புகைப்படம் எடுங்கள்",
    historyTitle: "சமீபத்திய உதவி",
    languageTitle: "உங்கள் மொழியைத் தேர்வுசெய்க",
    uploadTitle: "ஸ்கேன் செய்யுங்கள்",
    uploadDesc: "புகைப்படம் எடுக்கவும் அல்லது கேலரியிலிருந்து தேர்வுசெய்யவும்",
    takePhoto: "📷  புகைப்படம் எடு",
    chooseGallery: "🖼️  கேலரியிலிருந்து தேர்வுசெய்",
    analyzing: "உங்கள் புகைப்படத்தைப் படிக்கிறது...",
    resultTitle: "இதன் பொருள் இதுதான்",
    backHome: "🏠  முகப்புக்குச் செல்",
    scanAgain: "📷  மீண்டும் ஸ்கேன்",
    changeLang: "மொழியை மாற்று",
    textSize: "எழுத்து அளவு",
    listenButton: "🔊  கேளுங்கள்",
    stopButton: "⏹️  நிறுத்து",
  },
  hk: {
    appName: "SteadyLA",
    tagline: "我们帮你简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张照片，我们帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "选择语言",
    uploadTitle: "扫描东西",
    uploadDesc: "拍照或从相册选择",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选择",
    analyzing: "正在看你的照片...",
    resultTitle: "意思是这样的",
    backHome: "🏠  回首页",
    scanAgain: "📷  再扫描",
    changeLang: "更换语言",
    textSize: "文字大小",
    listenButton: "🔊  听一听",
    stopButton: "⏹️  停止",
  },
  ct: {
    appName: "SteadyLA",
    tagline: "我哋帮你简单解释",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "影张相，我哋帮你解释",
    historyTitle: "最近帮助",
    languageTitle: "拣语言",
    uploadTitle: "扫描嘢",
    uploadDesc: "影相或者从相册拣",
    takePhoto: "📷  影相",
    chooseGallery: "🖼️  从相册拣",
    analyzing: "睇紧你张相...",
    resultTitle: "意思系咁嘅",
    backHome: "🏠  返首页",
    scanAgain: "📷  再扫描",
    changeLang: "换语言",
    textSize: "文字大小",
    listenButton: "🔊  听下",
    stopButton: "⏹️  停",
  },
  tc: {
    appName: "SteadyLA",
    tagline: "阮共汝简单说明",
    scanButton: "📷  扫描 & 解释",
    scanSubtext: "拍张相，阮共汝解释",
    historyTitle: "最近帮助",
    languageTitle: "选语言",
    uploadTitle: "扫描物件",
    uploadDesc: "拍照或从相册选",
    takePhoto: "📷  拍照",
    chooseGallery: "🖼️  从相册选",
    analyzing: "在看汝的相片...",
    resultTitle: "意思是安呢",
    backHome: "🏠  转去首页",
    scanAgain: "📷  再扫描",
    changeLang: "换语言",
    textSize: "文字大小",
    listenButton: "🔊  听一下",
    stopButton: "⏹️  停",
  },
  vi: {
    appName: "SteadyLA",
    tagline: "Chúng tôi giúp bạn dễ hiểu hơn",
    scanButton: "📷  Quét & Giải thích",
    scanSubtext: "Chụp ảnh bất kỳ thứ gì bạn cần giúp đỡ",
    historyTitle: "Trợ giúp gần đây",
    languageTitle: "Chọn ngôn ngữ",
    uploadTitle: "Quét thứ gì đó",
    uploadDesc: "Chụp ảnh hoặc chọn từ thư viện",
    takePhoto: "📷  Chụp ảnh",
    chooseGallery: "🖼️  Chọn từ thư viện",
    analyzing: "Đang đọc ảnh của bạn...",
    resultTitle: "Đây là ý nghĩa",
    backHome: "🏠  Về trang chủ",
    scanAgain: "📷  Quét lại",
    changeLang: "Đổi ngôn ngữ",
    textSize: "Cỡ chữ",
    listenButton: "🔊  Nghe",
    stopButton: "⏹️  Dừng",
    othersTitle: "🌏  Other Languages",
  },
  th: {
    appName: "SteadyLA",
    tagline: "เราทำให้ง่ายสำหรับคุณ",
    scanButton: "📷  สแกน & อธิบาย",
    scanSubtext: "ถ่ายรูปสิ่งที่คุณต้องการความช่วยเหลือ",
    historyTitle: "ความช่วยเหลือล่าสุด",
    languageTitle: "เลือกภาษา",
    uploadTitle: "สแกนบางอย่าง",
    uploadDesc: "ถ่ายรูปหรือเลือกจากแกลเลอรี",
    takePhoto: "📷  ถ่ายรูป",
    chooseGallery: "🖼️  เลือกจากแกลเลอรี",
    analyzing: "กำลังอ่านรูปของคุณ...",
    resultTitle: "นี่คือความหมาย",
    backHome: "🏠  กลับหน้าหลัก",
    scanAgain: "📷  สแกนอีกครั้ง",
    changeLang: "เปลี่ยนภาษา",
    textSize: "ขนาดตัวอักษร",
    listenButton: "🔊  ฟัง",
    stopButton: "⏹️  หยุด",
    othersTitle: "🌏  Other Languages",
  },
  ko: {
    appName: "SteadyLA",
    tagline: "쉽게 설명해 드릴게요",
    scanButton: "📷  스캔 & 설명",
    scanSubtext: "도움이 필요한 것을 사진으로 찍어주세요",
    historyTitle: "최근 도움",
    languageTitle: "언어 선택",
    uploadTitle: "스캔하기",
    uploadDesc: "사진을 찍거나 갤러리에서 선택하세요",
    takePhoto: "📷  사진 찍기",
    chooseGallery: "🖼️  갤러리에서 선택",
    analyzing: "사진을 읽고 있어요...",
    resultTitle: "이런 뜻이에요",
    backHome: "🏠  홈으로",
    scanAgain: "📷  다시 스캔",
    changeLang: "언어 변경",
    textSize: "글자 크기",
    listenButton: "🔊  듣기",
    stopButton: "⏹️  멈추기",
    othersTitle: "🌏  Other Languages",
  },
  ja: {
    appName: "SteadyLA",
    tagline: "わかりやすくお伝えします",
    scanButton: "📷  スキャン＆説明",
    scanSubtext: "助けが必要なものを写真に撮ってください",
    historyTitle: "最近のヘルプ",
    languageTitle: "言語を選択",
    uploadTitle: "スキャンする",
    uploadDesc: "写真を撮るかギャラリーから選択",
    takePhoto: "📷  写真を撮る",
    chooseGallery: "🖼️  ギャラリーから選択",
    analyzing: "写真を読んでいます...",
    resultTitle: "こういう意味です",
    backHome: "🏠  ホームへ",
    scanAgain: "📷  もう一度スキャン",
    changeLang: "言語を変更",
    textSize: "文字サイズ",
    listenButton: "🔊  聴く",
    stopButton: "⏹️  停止",
    othersTitle: "🌏  Other Languages",
  },
  hi: {
    appName: "SteadyLA",
    tagline: "हम आपके लिए आसान बनाते हैं",
    scanButton: "📷  स्कैन और समझाएं",
    scanSubtext: "जिस चीज़ में मदद चाहिए उसकी फोटो लें",
    historyTitle: "हाल की मदद",
    languageTitle: "अपनी भाषा चुनें",
    uploadTitle: "कुछ स्कैन करें",
    uploadDesc: "फोटो लें या गैलरी से चुनें",
    takePhoto: "📷  फोटो लें",
    chooseGallery: "🖼️  गैलरी से चुनें",
    analyzing: "आपकी फोटो पढ़ रहे हैं...",
    resultTitle: "इसका मतलब यह है",
    backHome: "🏠  होम जाएं",
    scanAgain: "📷  फिर से स्कैन",
    changeLang: "भाषा बदलें",
    textSize: "अक्षर का आकार",
    listenButton: "🔊  सुनें",
    stopButton: "⏹️  रुकें",
    othersTitle: "🌏  Other Languages",
  },
};

export function t(lang: string, key: string): string {
  return translations[lang]?.[key] || translations.en[key] || key;
}
